version: '3.8'

services:
  # Eureka Naming Server - Ultra minimal
  naming-server:
    build:
      context: ./naming-server
    container_name: eureka-naming-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - microservice-network
    # Resource allocation
    mem_limit: 512m
    cpus: 0.5
    # Remove unnecessary features
    init: false
    tty: false
    stdin_open: false

  # User Service - Ultra minimal
  user-service:
    build:
      context: ./user-service
    container_name: user-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8761/eureka/
      # Spring Boot retry and startup configuration
      - EUREKA_CLIENT_INSTANCE_LEASE_RENEWAL_INTERVAL_IN_SECONDS=5
      - EUREKA_CLIENT_INSTANCE_LEASE_EXPIRATION_DURATION_IN_SECONDS=10
      - EUREKA_CLIENT_REGISTRY_FETCH_INTERVAL_SECONDS=3
      - EUREKA_CLIENT_INSTANCE_REGISTRATION_ENABLED=true
      - EUREKA_CLIENT_INITIAL_INSTANCE_INFO_REPLICATION_INTERVAL_SECONDS=5
      - EUREKA_CLIENT_EUREKA_SERVER_CONNECT_TIMEOUT_SECONDS=30
      - EUREKA_CLIENT_EUREKA_SERVER_READ_TIMEOUT_SECONDS=30
      # Spring Boot startup configuration
      - SPRING_CLOUD_DISCOVERY_CLIENT_FAIL_FAST=false
      - SPRING_CLOUD_DISCOVERY_CLIENT_REGISTER_HEALTH_INDICATOR=false
    networks:
      - microservice-network
    depends_on:
      - naming-server
    # Resource allocation
    mem_limit: 512m
    cpus: 0.5
    # Remove unnecessary features
    init: false
    tty: false
    stdin_open: false

  # User Service 8081 - Ultra minimal
  user-service-8081:
    build:
      context: ./user-service-8081
    container_name: user-service-8081
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8761/eureka/
      # Spring Boot retry and startup configuration
      - EUREKA_CLIENT_INSTANCE_LEASE_RENEWAL_INTERVAL_IN_SECONDS=5
      - EUREKA_CLIENT_INSTANCE_LEASE_EXPIRATION_DURATION_IN_SECONDS=10
      - EUREKA_CLIENT_REGISTRY_FETCH_INTERVAL_SECONDS=3
      - EUREKA_CLIENT_INSTANCE_REGISTRATION_ENABLED=true
      - EUREKA_CLIENT_INITIAL_INSTANCE_INFO_REPLICATION_INTERVAL_SECONDS=5
      - EUREKA_CLIENT_EUREKA_SERVER_CONNECT_TIMEOUT_SECONDS=30
      - EUREKA_CLIENT_EUREKA_SERVER_READ_TIMEOUT_SECONDS=30
      # Spring Boot startup configuration
      - SPRING_CLOUD_DISCOVERY_CLIENT_FAIL_FAST=false
      - SPRING_CLOUD_DISCOVERY_CLIENT_REGISTER_HEALTH_INDICATOR=false
    networks:
      - microservice-network
    depends_on:
      - naming-server
    # Resource allocation
    mem_limit: 512m
    cpus: 0.5
    # Remove unnecessary features
    init: false
    tty: false
    stdin_open: false

  # Hello Service - Ultra minimal
  hello-service:
    build:
      context: ./hello-service
    container_name: hello-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8761/eureka/
      # Spring Boot retry and startup configuration
      - EUREKA_CLIENT_INSTANCE_LEASE_RENEWAL_INTERVAL_IN_SECONDS=5
      - EUREKA_CLIENT_INSTANCE_LEASE_EXPIRATION_DURATION_IN_SECONDS=10
      - EUREKA_CLIENT_REGISTRY_FETCH_INTERVAL_SECONDS=3
      - EUREKA_CLIENT_INSTANCE_REGISTRATION_ENABLED=true
      - EUREKA_CLIENT_INITIAL_INSTANCE_INFO_REPLICATION_INTERVAL_SECONDS=5
      - EUREKA_CLIENT_EUREKA_SERVER_CONNECT_TIMEOUT_SECONDS=30
      - EUREKA_CLIENT_EUREKA_SERVER_READ_TIMEOUT_SECONDS=30
      # Spring Boot startup configuration
      - SPRING_CLOUD_DISCOVERY_CLIENT_FAIL_FAST=false
      - SPRING_CLOUD_DISCOVERY_CLIENT_REGISTER_HEALTH_INDICATOR=false
    networks:
      - microservice-network
    depends_on:
      - naming-server
      - user-service
    # Resource allocation
    mem_limit: 512m
    cpus: 0.5
    # Remove unnecessary features
    init: false
    tty: false
    stdin_open: false

networks:
  microservice-network:
    driver: bridge
